# GitHub Releases requires a tag
# :~$ git tag -s 1.0.19-1 -m "haveno-reto-v1.0.19-1-devel"
# :~$ git push origin 1.0.19-1
name: ACAFB

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
#       if: startsWith(github.ref, 'refs/tags/')
        with:
#         target_commitish: haveno-reto-dev
          files: |
            seednode/build/distributions/seednode.tar
            ${{ github.workspace }}/release-linux-deb/haveno-v${{ env.VERSION }}-linux-x86_64-installer.deb
            ${{ github.workspace }}/desktop/build/temp-*/binaries/desktop-${{ env.VERSION }}-SNAPSHOT-all.jar.SHA-256

#           ${{ github.workspace }}/release-linux-deb/*
